config/routes.rb
Imobify::Application.routes.draw do
  root to: 'realties#index'

  resources :realties, path: 'imoveis', only: :show

  namespace :admin do
    devise_for :users, controllers: {sessions: 'admin/sessions'}

    root to: 'realties#index'

    resources :realties, only: [:index, :create, :edit, :update] do
      resources :photos, only: [:create, :destroy]

      put :publish
      put :deactivate
    end

    resources :countries, only: [] do
      resources :cities, only: :index
    end
  end
end

app/models/realty.rb
class Realty < ActiveRecord::Base
  BUSINESS_KIND = %w(sale rental vacation_rental)
  REALTY_KIND   = %w(house apartment kitchenette room store terrain country_house site farm)
  STATUS        = %w(published draft deactivated)

  NUMERIC_FIELDS   = %i(rooms bathrooms parking_spaces size price taxes)
  TEXT_FIELDS      = %i(neighborhood street business_kind realty_kind status reference)
  PERMITTED_FIELDS = NUMERIC_FIELDS + TEXT_FIELDS + %i(country_id city_id description)

  acts_as_tenant :account

  belongs_to :country, required: true
  belongs_to :city,    required: true

  has_many :photos, dependent: :destroy

  validates :account, presence: true
  validates :views,   presence: true, numericality: {only_integer: true}

  validates :business_kind, inclusion: BUSINESS_KIND, allow_nil: true
  validates :realty_kind,   inclusion: REALTY_KIND,   allow_nil: true
  validates :status,        inclusion: STATUS,        allow_nil: true

  validates *NUMERIC_FIELDS, numericality: {only_integer: true}, allow_nil: true
  validates *TEXT_FIELDS,    length: {maximum: 255}

  scope :published, -> { where(status: 'published') }

  %i(business_kind realty_kind city_id rooms parking_spaces).each do |field|
    scope "by_#{field}".to_sym, -> (value) { where(field => value) if value.present? }
  end

  class << self
    def new_with_last_locations
      any? ? new(last.attributes.extract!('country_id', 'city_id')) : new
    end

    def find_and_count(id)
      find(id).tap { |r| r.increment! :views }
    end
  end

  def related_realties
    self.class.published.by_city_id(city_id).by_business_kind(business_kind).where.not(id: id)
  end

  def locations
    Country.all_with_cities_by(country)
  end

  def location
    [neighborhood, city.full_name].reject(&:blank?).join(' - ')
  end

  def full_location
    [street, location].reject(&:blank?).join(' - ')
  end

  def cover_url(version)
    photo = photos.first
    photo.file.send(version).url if photo.present?
  end

  def kind
    return if realty_kind.blank? || business_kind.blank?

    i18n = I18n.t('activerecord.collections.realty')

    bk = i18n[:business_kind][business_kind.to_sym]
    rk = i18n[:realty_kind][realty_kind.to_sym]

    [rk, bk].join(' ')
  end

  def have_summary?
    %i(rooms bathrooms parking_spaces size).each do |field|
      return true if send(field).present?
    end

    false
  end

  def publish!
    update_attribute(:status, 'published')
  end

  def published?
    status == 'published'
  end

  def deactivate!
    update_attribute(:status, 'deactivated')
  end

  def deactivated?
    status == 'deactivated'
  end
end

app/controllers/admin/realties_controller.rb
class Admin::RealtiesController < Admin::AdminController
  def index
    @realty   = Realty.new_with_last_locations
    @realties = Realty.order(created_at: :desc)

    respond_with
  end

  def create
    respond_with @realty = Realty.create(realty_params), location: edit_admin_realty_path(@realty)
  end

  def edit
    respond_with @realty = Realty.find(params[:id])
  end

  def update
    respond_with @realty = Realty.update(params[:id], realty_params), location: admin_realties_path
  end

  def publish
    respond_with @realty = Realty.find(params[:realty_id]).publish!, location: admin_realties_path
  end

  def deactivate
    respond_with @realty = Realty.find(params[:realty_id]).deactivate!, location: admin_realties_path
  end

  private

  def realty_params
    params.require(:realty).permit(*Realty::PERMITTED_FIELDS)
  end
end

app/controllers/realties_controller.rb
class RealtiesController < ApplicationController
  def index
    @search   = RealtySearch.new(params[:realty_search])
    @realties = @search.result.order(created_at: :desc)

    render_template
  end

  def show
    @realty = Realty.published.find_and_count(params[:id])

    render_template
  end
end

app/helpers/realty_helper.rb
module RealtyHelper
  def cover_path_for(realty, version)
    realty.cover_url(version) || image_path('admin/no_cover_bg.png')
  end
end

app/views/admin/realties/_new.html.erb
<div class="modal fade" id="new-realty" tabindex="-1" role="dialog" aria-labelledby="new-realty-title" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for [:admin, @realty] do |f| %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="new-realty-title">Novo Imóvel</h4>
        </div>

        <div class="modal-body">
          <p>Comece informando a localidade do Imóvel.</p>

          <div class="row">
            <div class="col-xs-12 col-sm-6">
              <div class="form-group">
                <%= f.label :country_id %>
                <%= f.collection_select(:country_id, @realty.locations[:countries], :id, :name, {}, {class: 'form-control'}) %>
                <small class="help-block">Ao selecionar um Estado, a lista de Cidades será atualizada.</small>
              </div>
            </div>

            <div class="col-xs-12 col-sm-6">
              <div class="form-group">
                <%= f.label :city_id %>
                <%= f.collection_select(:city_id, @realty.locations[:cities], :id, :name, {}, {class: 'form-control'}) %>
                <small class="help-block">A lista de Cidades está em ordem alfabética.</small>
              </div>
            </div>
          </div>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
          <%= f.submit 'Avançar para Edição...', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/realties/edit.html.erb
<h1>Editar Imóvel</h1>
<p>Aqui você pode preencher a localização, dados básicos, detalhes e adicionar fotos ao imóvel.</p>

<div class="row">
  <div class="col-xs-12 col-md-9 col-lg-8">
    <%= form_for [:admin, @realty] do |f| %>
      <%= def resource; @realty; end; devise_error_messages! %>

      <fieldset>
        <legend>Localização</legend>

        <div class="row">
          <div class="col-xs-12 col-sm-6">
            <div class="form-group">
              <%= f.label :country_id %>
              <%= f.collection_select(:country_id, @realty.locations[:countries], :id, :name, {}, {class: 'form-control'}) %>
            </div>
          </div>

          <div class="col-xs-12 col-sm-6">
            <div class="form-group">
              <%= f.label :city_id %>
              <%= f.collection_select(:city_id, @realty.locations[:cities], :id, :name, {}, {class: 'form-control'}) %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12 col-sm-6">
            <div class="form-group">
              <%= f.label :neighborhood %>
              <%= f.text_field :neighborhood, class: 'form-control' %>
            </div>
          </div>

          <div class="col-xs-12 col-sm-6">
            <div class="form-group">
              <%= f.label :street %>
              <%= f.text_field :street, class: 'form-control' %>
            </div>
          </div>
        </div>
      </fieldset>

      <fieldset>
        <legend>Dados Básicos</legend>

        <div class="row">
          <div class="col-xs-12 col-sm-4">
            <div class="form-group">
              <%= f.label :business_kind %>
              <%= f.select(:business_kind, Realty::BUSINESS_KIND.collect do |bk|
                [t("activerecord.collections.realty.business_kind.#{bk}").split.last, bk]
              end, {}, {class: 'form-control'}) %>
            </div>
          </div>

          <div class="col-xs-12 col-sm-4">
            <div class="form-group">
              <%= f.label :realty_kind %>
              <%= f.select(:realty_kind, Realty::REALTY_KIND.collect do |rk|
                [t("activerecord.collections.realty.realty_kind.#{rk}"), rk]
              end, {}, {class: 'form-control'}) %>
            </div>
          </div>

          <div class="col-xs-12 col-sm-4">
            <div class="form-group">
              <%= f.label :reference %>
              <%= f.text_field :reference, class: 'form-control' %>
            </div>
          </div>
        </div>
      </fieldset>

      <fieldset>
        <legend>Mais Detalhes</legend>

        <div class="row">
          <div class="col-xs-12 col-md-6">
            <div class="row">
              <div class="col-xs-12 col-sm-6">
                <div class="form-group">
                  <%= f.label :rooms %>
                  <%= f.text_field :rooms, class: 'form-control integer' %>
                </div>
              </div>

              <div class="col-xs-12 col-sm-6">
                <div class="form-group">
                  <%= f.label :bathrooms %>
                  <%= f.text_field :bathrooms, class: 'form-control integer' %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-xs-12 col-sm-6">
                <div class="form-group">
                  <%= f.label :parking_spaces %>
                  <%= f.text_field :parking_spaces, class: 'form-control integer' %>
                </div>
              </div>

              <div class="col-xs-12 col-sm-6">
                <div class="form-group">
                  <%= f.label :size %>

                  <div class="input-group">
                    <%= f.text_field :size, class: 'form-control integer right' %>
                    <span class="input-group-addon">m²</span>
                  </div>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-xs-12 col-sm-6">
                <div class="form-group">
                  <%= f.label :price %>

                  <div class="input-group">
                    <span class="input-group-addon">R$</span>
                    <%= f.text_field :price, class: 'form-control integer right' %>
                    <span class="input-group-addon">,00</span>
                  </div>
                </div>
              </div>

              <div class="col-xs-12 col-sm-6">
                <div class="form-group">
                  <%= f.label :taxes %>

                  <div class="input-group">
                    <span class="input-group-addon">R$</span>
                    <%= f.text_field :taxes, class: 'form-control integer right' %>
                    <span class="input-group-addon">,00</span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-xs-12 col-md-6">
            <div class="form-group">
              <%= f.label :description %>
              <%= f.text_area :description, class: 'form-control' %>
            </div>
          </div>
        </div>
      </fieldset>

      <fieldset class="photos">
        <legend>Fotos</legend>

        <div class="row">
          <div class="col-xs-12 col-md-4">
            <p>Para adicionar as fotos do Imóvel, clique no botão abaixo e selecione-as de seu computador ou galeria.</p>

            <div class="btn btn-primary fileinput-button">
              <span>Selecionar Fotos...</span>
              <input type="file" name="photo[]" data-url="photos" accept="image/*" multiple="true">
            </div>
          </div>

          <div class="col-xs-12 col-md-8">
            <p id="trash" class="alert alert-warning center<%= ' hide' if @realty.photos.none? %>">
              <%= glyph(:trash, {}) %> Para excluir uma foto, arraste-a para cá.
            </p>

            <p class="text-muted<%= ' hide' if @realty.photos.any? %>">
              Você ainda não adicionou fotos.
            </p>

            <div id="photos-container"<%= ' class=not-empty' if @realty.photos.any? %>>
              <% @realty.photos.each_with_index do |photo, i| %>
                <%= image_tag photo.file.admin_thumb.url, alt: 'Foto', class: 'img-thumbnail photo', data: {:'mfp-src' => photo.file.normal.url, :'photo-id' => photo.id, index: i} %>
              <% end %>
            </div>
          </div>
        </div>
      </fieldset>

      <div class="row">
        <div class="col-xs-12 col-md-6">
          <fieldset>
            <legend>Publicar no Site</legend>

            <p>Ao publicar o Imóvel, ele ficará visível no seu Site. Para mantê-lo apenas cadastrado no Painel de Controle e sem aparecer no Site, marque-o como <i>Rascunho</i>.</p>

            <div class="form-group">
              <%= f.select(:status, Realty::STATUS.collect do |st|
                [t("activerecord.collections.realty.status.#{st}"), st]
              end, {}, {class: 'form-control'}) %>
            </div>
          </fieldset>
        </div>

        <div class="col-xs-12 col-md-6">
          <fieldset>
            <legend>Finalizar</legend>

            <p>Ao clicar no botão abaixo, todas as informações estarão salvas e prontas para serem exibidas no Site assim que o Imóvel for publicado.</p>

            <%= f.submit 'Concluir Edição', class: 'btn btn-lg btn-primary btn-block' %>
          </fieldset>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-md-3 col-lg-4 hide">
    <h4>Veja Algumas Dicas</h4>

    <p>Localização</p>
    <small class="help-block">É interessante o preenchimento dos campos Bairro e Logradouro para que o cliente tenha a oportunidade de procurar mais sobre as proximidades. Contudo, não é recomendado dispor do endereço completo do Imóvel por questões de segurança.</small>

    <p>Código do Imóvel</p>
    <small class="help-block">Opcional. Apenas uma referência interna para fácil organização.</small>

    <p>Valor e Outras Taxas</p>
    <small class="help-block">O campo Valor serve tanto para quantias de aluguel mensal quanto de vendas. Use o campo Outras Taxas para especificar despesas como Condomínio, IPTU e etc.</small>

    <p>Descrição do Imóvel</p>
    <small class="help-block">Seja bem detalhista aqui. Mesmo havendo campos para informações específicas, é importante repetí-las na descrição para que os sites de busca (como o Google) consigam listar seus imóveis com maior eficiência.</small>

    <p>Fotos</p>
    <small class="help-block">Escolha fotos com uma boa qualidade, mas tome cuidado com fotos em alta resolução, pois podem acarretar em um tempo de carregamento maior e também consumir excessivamente sua franquia de dados caso esteja utilizando uma conexão móvel como a 3G.</small>
  </div>
</div>

app/views/admin/realties/index.html.erb
<%= render 'new' %>

<% if @realties.any? %>
  <h1>
    Imóveis
    <button type="button" class="btn btn-sm btn-primary btn-new" data-toggle="modal" data-target="#new-realty">
      <%= glyph(:plus, {}) %> Novo Imóvel
    </button>
  </h1>

  <p>Aqui você encontra todos os imóveis cadastrados e pode gerenciá-los com facilidade.</p>

  <div class="row realties">
    <% @realties.each do |realty| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="realty" style="background-image: url(<%= cover_path_for(realty, :admin_cover) %>)">
          <% if realty.reference.present? %>
            <span class="label label-info reference"><%= realty.reference %></span>
          <% end %>

          <% if realty.published? %>
            <span class="label label-success">Publicado</span>
          <% elsif realty.deactivated? %>
            <span class="label label-default">Desativado</span>
          <% else %>
            <span class="label label-info">Rascunho</span>
          <% end %>

          <% if realty.cover_url(:admin_cover).blank? %>
            <span class="label label-danger">Sem Fotos</span>
          <% end %>

          <div>
            <div class="btn-group pull-right">
              <%= link_to 'Editar', edit_admin_realty_path(realty), class: 'btn btn-xs btn-primary' %>

              <% unless realty.deactivated? %>
                <button type="button" class="btn btn-xs btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  <span class="caret"></span>
                  <span class="sr-only">Alternar Menu</span>
                </button>

                <ul class="dropdown-menu" role="menu">
                  <% unless realty.published? %>
                    <li>
                      <%= link_to 'Publicar Imóvel', admin_realty_publish_path(realty), data: {method: :put, confirm: 'Tem certeza de que deseja publicar este Imóvel? Ele irá aparecer no seu Site imediatamente.'} %>
                    </li>
                  <% end %>

                  <li>
                    <%= link_to 'Desativar Imóvel', admin_realty_deactivate_path(realty), data: {method: :put, confirm: 'Tem certeza de que deseja desativar este Imóvel? Ele não irá mais aparecer no seu Site.'} %>
                  </li>
                </ul>
              <% end %>
            </div>

            <% if realty.kind.present? %>
              <p><%= realty.kind %></p>
            <% end %>

            <p><%= realty.location %></p>

            <% if realty.price.present? %>
              <p><%= to_currency(realty.price) %></p>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="jumbotron">
    <h1>Seja bem vindo ao <b>Painel de Controle</b> do seu site.</h1>

    <p>Para começar a cadastrar sua coleção de imóveis, clique no botão abaixo e siga as instruções das telas que se seguem. Se você tiver alguma dúvida, não hesite em entrar em contato.</p>

    <button type="button" class="btn btn-lg btn-primary" data-toggle="modal" data-target="#new-realty">
      <%= glyph(:plus, {}) %> Novo Imóvel
    </button>
  </div>
<% end %>