config/routes.rb
Imobify::Application.routes.draw do
  root to: 'realties#index'

  resources :realties, path: 'imoveis', only: :show

  namespace :admin do
    devise_for :users, controllers: {sessions: 'admin/sessions'}

    root to: 'realties#index'

    resources :realties, only: [:index, :create, :edit, :update] do
      resources :photos, only: [:create, :destroy]

      put :publish
      put :deactivate
    end

    resources :countries, only: [] do
      resources :cities, only: :index
    end
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <meta name="image-loading" content="<%= image_path 'admin/loading.gif' %>">
    <title><%= current_tenant.site_settings.title %> - Painel de Controle</title>
    <%= stylesheet_link_tag "admin", media: "all" %>
    <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="<%= "#{controller_name}-#{action_name}" %>">
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <% if current_admin_user.present? %>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Alternar Menu</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          <% end %>
          <%= link_to current_tenant.site_settings.title, admin_root_path, class: 'navbar-brand' %>
        </div>
        <% if current_admin_user.present? %>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <%= menu_link_to 'Imóveis', admin_realties_path %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><p class="navbar-text logged-user">Olá, <%= current_admin_user.username %>!</p></li>
              <%= menu_link_to 'Ir ao Site', root_path %>
              <%= menu_link_to 'Sair', destroy_admin_user_session_path, data: {method: :delete} %>
            </ul>
          </div>
        <% end %>
      </div>
    </div>

    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>

    <%= javascript_include_tag "admin" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Nova App</title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Alternar Menu</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Nova App', root_path, class: 'navbar-brand' %>
        </div>
        <div class="navbar-collapse collapse">
          <% if current_user.present? %>
            <ul class="nav navbar-nav">
              <%= menu_link_to 'Usuários', users_path %>
            </ul>
          <% end %>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user.present? %>
              <%= menu_link_to 'Sair', destroy_user_session_path, data: {method: :delete} %>
            <% else %>
              <%= menu_link_to 'Entrar', new_user_session_path %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>